[package]
name = "hello-salvo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
salvo = {version = "0.24.4" , features=["serve-static"]}
tokio = {version = "1", features = ["full"]}
